-- MySQL Script generated by MySQL Workbench
-- Wed Sep  6 14:58:27 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema exercise_looper
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema exercise_looper
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `exercise_looper` DEFAULT CHARACTER SET utf8;
USE `exercise_looper`;

-- -----------------------------------------------------
-- Table `exercise_looper`.`excercises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_looper`.`excercises`
(
    `id`                INT                                      NOT NULL AUTO_INCREMENT,
    `title`             TINYTEXT                                 NOT NULL,
    `status`            ENUM ('building', 'answering', 'closed') NOT NULL,
    `creation_date`     DATETIME                                 NOT NULL,
    `modification_date` DATETIME,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_looper`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_looper`.`questions`
(
    `id`            INT                                                    NOT NULL AUTO_INCREMENT,
    `excercises_id` INT                                                    NOT NULL,
    `title`         VARCHAR(45)                                            NOT NULL,
    `type`          ENUM ('single_line', 'single_line_list', 'multi_line') NOT NULL,
    PRIMARY KEY (`excercises_id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
    INDEX `fk_questions_excercises1_idx` (`excercises_id` ASC) VISIBLE,
    CONSTRAINT `fk_questions_excercises1`
        FOREIGN KEY (`excercises_id`)
            REFERENCES `exercise_looper`.`excercises` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_looper`.`fulfillments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_looper`.`fulfillments`
(
    `id`              INT         NOT NULL AUTO_INCREMENT,
    `timestamp`       TINYTEXT    NULL,
    `fulfillmentscol` VARCHAR(45) NULL,
    `excercises_id`   INT         NOT NULL,
    PRIMARY KEY (`id`, `excercises_id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
    UNIQUE INDEX `fulfillmentscol_UNIQUE` (`fulfillmentscol` ASC) VISIBLE,
    INDEX `fk_fulfillments_excercises_idx` (`excercises_id` ASC) VISIBLE,
    CONSTRAINT `fk_fulfillments_excercises`
        FOREIGN KEY (`excercises_id`)
            REFERENCES `exercise_looper`.`excercises` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_looper`.`answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_looper`.`answers`
(
    `id`                         INT         NOT NULL AUTO_INCREMENT,
    `questions_id`               INT         NOT NULL,
    `fulfillments_id`            INT         NOT NULL,
    `fulfillments_excercises_id` INT         NOT NULL,
    `answer`                     VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`, `questions_id`, `fulfillments_id`, `fulfillments_excercises_id`),
    INDEX `fk_questions_has_fulfillments_fulfillments1_idx` (`fulfillments_id` ASC, `fulfillments_excercises_id` ASC) VISIBLE,
    INDEX `fk_questions_has_fulfillments_questions1_idx` (`questions_id` ASC) VISIBLE,
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
    CONSTRAINT `fk_questions_has_fulfillments_questions1`
        FOREIGN KEY (`questions_id`)
            REFERENCES `exercise_looper`.`questions` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_questions_has_fulfillments_fulfillments1`
        FOREIGN KEY (`fulfillments_id`, `fulfillments_excercises_id`)
            REFERENCES `exercise_looper`.`fulfillments` (`id`, `excercises_id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
