use exercise_looper;
insert into questions (id, exercises_id, title, type) values (1, 1, 'Jim Norton: Please Be Offended', 'single_line');
insert into questions (id, exercises_id, title, type) values (2, 2, 'Our Dancing Daughters', 'single_line_list');
insert into questions (id, exercises_id, title, type) values (3, 3, 'Harem suare', 'single_line_list');
insert into questions (id, exercises_id, title, type) values (4, 4, 'Yumeji', 'single_line_list');
insert into questions (id, exercises_id, title, type) values (5, 5, 'Charter Trip', 'single_line_list');
insert into questions (id, exercises_id, title, type) values (6, 6, 'Goodbye Girl, The', 'multi_line');
insert into questions (id, exercises_id, title, type) values (7, 7, 'Camera Buff (Amator)', 'single_line');
insert into questions (id, exercises_id, title, type) values (8, 8, 'Casablanca', 'single_line_list');
insert into questions (id, exercises_id, title, type) values (9, 9, 'What Would Jesus Buy?', 'multi_line');
insert into questions (id, exercises_id, title, type) values (10, 10, 'Divorce of Lady X, The', 'single_line_list');
insert into questions (id, exercises_id, title, type) values (11, 11, 'Conversations with My Gardener', 'single_line');
insert into questions (id, exercises_id, title, type) values (12, 12, 'National Lampoon''s Vacation', 'single_line');
insert into questions (id, exercises_id, title, type) values (13, 13, 'Kill List', 'multi_line');
insert into questions (id, exercises_id, title, type) values (14, 14, 'Destination Gobi', 'multi_line');
insert into questions (id, exercises_id, title, type) values (15, 15, 'Outrageous Class (Hababam sinifi)', 'multi_line');
insert into questions (id, exercises_id, title, type) values (16, 16, 'Night to Remember, A', 'single_line');
insert into questions (id, exercises_id, title, type) values (17, 17, 'Why Has Bodhi-Dharma Left for the East?', 'single_line');
insert into questions (id, exercises_id, title, type) values (18, 18, 'Fear of Flying', 'single_line_list');
insert into questions (id, exercises_id, title, type) values (19, 19, 'Gestapo', 'single_line_list');
insert into questions (id, exercises_id, title, type) values (20, 20, 'Castle, The', 'single_line_list');